name: Releaser

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  merge-checker:
    runs-on: ubuntu-latest
    outputs:
      merge-commit: ${{ steps.merge-commit.outputs.result }}
    steps:
      - uses: actions/checkout@v7

      - name: Detect if merge commit
        id: merge-commit
        run: |
          MSG=$(git log -1 --pretty=%s)
          if [[ "$MSG" =~ ^Merge\ pull\ request ]]; then
            echo "result=true" >> "$GITHUB_OUTPUT"
          else
            echo "result=false" >> "$GITHUB_OUTPUT"
          fi

  # Builds package a, first thing in tree
  package-a:
    needs: merge-checker
    if: needs.merge-checker.outputs.merge-commit == 'true'
    outputs:
      releases-created: ${{ steps.release.outputs.releases_created }}
      version: ${{ steps.release.outputs.a--version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: release-please-a.json
          token: ${{ secrets.GITHUB_TOKEN }}

  # Builds package b, next in tree, also des a commit to make sure
  package-b:
    needs:
      - package-a
      - merge-checker
    if: needs.merge-checker.outputs.merge-commit == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-go@v7
        with:
          go-version-file: b/go.mod

      # Commit with the newest version first
      - name: Commit new version for a
        if: needs.package-a.outputs.version != ''
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          cd b
          go get github.com/Unbreathable/staggered/a@v${{ needs.package-a.outputs.version }}
          go mod tidy
          cd ..
          git add b/go.mod b/go.sum
          git commit -m "chore: upgrade a"
          git pull --rebase origin ${{ github.head_ref || github.ref_name }}
          git push origin HEAD:${{ github.head_ref || github.ref_name }}

      # Then actually release b
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: release-please-b.json
          token: ${{ secrets.GITHUB_TOKEN }}
