name: Updater

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect if merge commit
        id: merge_check
        run: |
          MSG=$(git log -1 --pretty=%s)
          if [[ "$MSG" =~ ^Merge\ pull\ request ]]; then
            echo "result=true" >> "$GITHUB_OUTPUT"
          else
            echo "result=false" >> "$GITHUB_OUTPUT"
          fi

      - uses: googleapis/release-please-action@v4
        id: release
        if: steps.merge_check.outputs.result == 'false'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
